import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth'

const Auth = ({ mode }) => {
  const isSignup = mode === 'signup'; const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const { signIn, signUp } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const submit = async (event) => { event.preventDefault(); setError(''); if (!/^\S+@\S+\.\S+$/.test(form.email) || form.password.length < 8 || (isSignup && !form.name.trim())) return setError(isSignup ? 'Enter your name, a valid email, and a password of at least 8 characters.' : 'Enter a valid email and password of at least 8 characters.'); try { await (isSignup ? signUp(form) : signIn(form)); navigate(location.state?.from || '/') } catch (err) { setError(err.message) } }
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-6"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl"><div className="mb-8 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-600 font-bold text-white">SMS</div><div><h1 className="font-bold text-slate-900">Student Management</h1><p className="text-sm text-slate-500">Secure academic operations</p></div></div><h2 className="text-2xl font-semibold text-slate-900">{isSignup ? 'Create your account' : 'Welcome back'}</h2><p className="mt-1 text-sm text-slate-500">{isSignup ? 'Set up the first administrator account.' : 'Sign in to manage your student records.'}</p><form onSubmit={submit} className="mt-6 space-y-4">{isSignup && <label className="block text-sm font-medium">Full name<input className="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label>}<label className="block text-sm font-medium">Email<input type="email" className="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label className="block text-sm font-medium">Password<input type="password" className="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button className="w-full rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white hover:bg-blue-700">{isSignup ? 'Create account' : 'Sign in'}</button></form><p className="mt-6 text-center text-sm text-slate-500">{isSignup ? 'Already registered? ' : 'Need an account? '}<Link className="font-semibold text-blue-600" to={isSignup ? '/login' : '/signup'}>{isSignup ? 'Sign in' : 'Create one'}</Link></p></div></main>
}
export const Login = () => <Auth mode="login" />
export const Signup = () => <Auth mode="signup" />
